name: Scrape and Update Json
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/30 13-18 * * *'
jobs:
  update-json:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
    - uses: actions/checkout@v2
    - name: update-json
      run: bash updatejson.sh && echo "the job completed"
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
